name: Deploy Backend to Production ECS

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      image_tag:
        description: Image tag used to deploy
        required: true
        default: latest

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4